# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, pkgs, modulesPath, ... }:

let
  unstable = import inputs.nixos-unstable {
    system = pkgs.stdenv.hostPlatform.system;
    config = config.nixpkgs.config;
  };

  # Full linux-firmware pinned to 20260110 (known-good for s2idle on AMD AI 300).
  # Injected first in hardware.firmware so it wins all file collisions.
  linux-firmware-20260110 = pkgs.linux-firmware.overrideAttrs (_: {
    version = "20260110";
    src = pkgs.fetchzip {
      url = "https://gitlab.com/kernel-firmware/linux-firmware/-/archive/20260110/linux-firmware-20260110.tar.gz";
      hash = "sha256-zL2ck91IBjBw/10YirxfoScEjbvEXVBR7bpLzuF3kDc=";
    };
  });

in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      "${inputs.nixos-hardware}/framework/13-inch/amd-ai-300-series/"
      inputs.ucodenix.nixosModules.default
    ];

  boot.kernelPackages = pkgs.linuxPackages_6_18;

  # wifi issues
  # https://chatgpt.com/share/69416726-23f8-8010-b19b-ae042297289a
  # hardware.enableRedistributableFirmware = true;
  # networking.networkmanager = {
  #  enable = true;
  #  wifi.powersave = false;
  #  # wifi.backend = "iwd";
  # };
  # boot.extraModprobeConfig = ''
  #  options iwlwifi power_save=0
  #  options iwlwifi uapsd_disable=1
  #  options iwlwifi disable_11ax=1
  # '';

  hardware.framework.laptop13.audioEnhancement.enable = true;
  hardware.framework.laptop13.audioEnhancement.hideRawDevice = false;

  services.ucodenix.enable = true;
  boot.kernelParams = [ "microcode.amd_sha_check=off" "amdgpu.sg_display=0" ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/73d0694e-c4b4-4611-80a9-8d8d38d59b1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-96baacf0-b474-4836-852c-8defe41909ad".device =
    "/dev/disk/by-uuid/96baacf0-b474-4836-852c-8defe41909ad";

  boot.initrd.luks.devices."luks-f93c075a-47bc-46e7-af18-400201a7680f".device =
    "/dev/disk/by-uuid/f93c075a-47bc-46e7-af18-400201a7680f";

	fileSystems."/boot" =
	  { device = "/dev/disk/by-uuid/98D4-90BE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1cdec3e4-5364-4796-b6d5-9ed4ccdc7d55"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # trying this
  # boot.kernelParams = ["amdgpu.mes=0" "amdgpu.gpu_recovery=1"];
  services.fwupd.enable = true;

  # ===== Fix: s2idle suspend/resume freeze (AMD AI 300 / Strix Point) =====
  # linux-firmware 20260221 introduced regressions that prevent S0ix:
  # - amdgpu/dcn_3_5_1_dmcub.bin: DMCUB regression blocks AMD PMC S0ix handshake
  # - amdnpu/1502_00/npu.sbin: NPU firmware 1.5.5.391 protocol incompatible with amdxdna
  # - intel/ibt-0041-0041.sfi: BT regression may block USB xHCI from entering D3
  # Rather than chasing individual files, pin the entire linux-firmware to 20260110
  # (the last known-good version) by injecting it FIRST in hardware.firmware.
  # The aggregation uses ignoreCollisions=true / first-wins, so 20260110 files
  # take precedence; any NEW files only in 20260221 still get included.
  hardware.firmware = lib.mkBefore [ linux-firmware-20260110 ];
}
