# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, config, lib, pkgs, modulesPath, ... }:

let
  unstable = import inputs.nixos-unstable {
    system = pkgs.stdenv.hostPlatform.system;
    config = config.nixpkgs.config;
  };

in
{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      "${inputs.nixos-hardware}/framework/13-inch/amd-ai-300-series/"
      inputs.ucodenix.nixosModules.default
    ];

  # wifi issues
  # https://chatgpt.com/share/69416726-23f8-8010-b19b-ae042297289a
  # boot.kernelPackages = pkgs.linuxPackages_6_18;
  # hardware.enableRedistributableFirmware = true;
  # networking.networkmanager = {
  #  enable = true;
  #  wifi.powersave = false;
  #  # wifi.backend = "iwd";
  # };
  # boot.extraModprobeConfig = ''
  #  options iwlwifi power_save=0
  #  options iwlwifi uapsd_disable=1
  #  options iwlwifi disable_11ax=1
  # '';

  hardware.framework.laptop13.audioEnhancement.enable = true;
  hardware.framework.laptop13.audioEnhancement.hideRawDevice = false;

  services.ucodenix.enable = true;
  boot.kernelParams = [ "microcode.amd_sha_check=off" "amdgpu.sg_display=0" ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/73d0694e-c4b4-4611-80a9-8d8d38d59b1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-96baacf0-b474-4836-852c-8defe41909ad".device =
    "/dev/disk/by-uuid/96baacf0-b474-4836-852c-8defe41909ad";

  boot.initrd.luks.devices."luks-f93c075a-47bc-46e7-af18-400201a7680f".device =
    "/dev/disk/by-uuid/f93c075a-47bc-46e7-af18-400201a7680f";

	fileSystems."/boot" =
	  { device = "/dev/disk/by-uuid/98D4-90BE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1cdec3e4-5364-4796-b6d5-9ed4ccdc7d55"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # trying this
  # boot.kernelParams = ["amdgpu.mes=0" "amdgpu.gpu_recovery=1"];
  services.fwupd.enable = true;

  # ===== Fix: AX210 s2idle suspend/resume freeze =====
  # The AX210 (firmware 89.x) fails to resume from s2idle. Its registers return
  # 0x5a5a5a5a (device unresponsive), causing iwl_fw_dbg_collect_sync to spin
  # on dead hardware, triggering an RCU stall and full system freeze.
  # See: https://community.frame.work/t/framework-13-ai-300-series-wont-resume-most-of-the-time/72695

  # Safety net: disable debug dump (prevents RCU stall) and cleanly remove dead device
  boot.extraModprobeConfig = ''
    options iwlwifi enable_ini=0 remove_when_gone=1
    options iwlmvm power_scheme=1
  '';

  # Firmware 89.x introduced the s2idle resume regression. Removing it forces
  # the kernel to fall back to 86.x, which doesn't have the bug.
  nixpkgs.overlays = [
    (_final: prev: {
      linux-firmware = prev.linux-firmware.overrideAttrs (old: {
        postInstall = (old.postInstall or "") + ''
          rm -f $out/lib/firmware/intel/iwlwifi/iwlwifi-ty-a0-gf-a0-89.ucode.zst
        '';
      });
    })
  ];

  # ===== Fallback workaround (try if firmware downgrade above is insufficient) =====
  # Unloading the driver before sleep bypasses the broken resume path entirely,
  # at the cost of a WiFi reconnect delay on every wake. Also requires disabling
  # D3cold (the udev rule below) so PCIe doesn't power-gate the card while unloaded.
  #
  # systemd.services."iwlwifi-pre-suspend" = {
  #   description = "Unload iwlwifi before sleep";
  #   before = [ "sleep.target" ];
  #   wantedBy = [ "sleep.target" ];
  #   serviceConfig = {
  #     Type = "oneshot";
  #     ExecStart = "${pkgs.kmod}/bin/modprobe -r iwlmvm iwlwifi";
  #   };
  # };
  #
  # powerManagement.resumeCommands = ''
  #   ${pkgs.kmod}/bin/modprobe iwlwifi
  #   ${pkgs.kmod}/bin/modprobe iwlmvm
  # '';
  #
  # services.udev.extraRules = ''
  #   ACTION=="add", SUBSYSTEM=="pci", DRIVER=="iwlwifi", ATTR{d3cold_allowed}="0"
  # '';
}
