general {
    before_sleep_cmd = brightnessctl -r
    after_sleep_cmd = brightnessctl -r
}

# Dim screen after 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Suspend after 20 minutes (battery only)
listener {
    timeout = 1200
    on-timeout = grep -q 0 /sys/class/power_supply/AC*/online && systemctl suspend
}
