#!/usr/bin/env bash

set -euo pipefail

# Where to write the file
ENV_FILE="$HOME/.config/hypr/env.conf"

# Make sure the directory exists
mkdir -p "$(dirname "$ENV_FILE")"

# Query scale of first monitor (integer part only)
SCALE=$(hyprctl -j monitors | jq -r '.[0].scale' | cut -d. -f1)

# Fallback to 1 if nothing was detected
[ -z "$SCALE" ] && SCALE=1

# Write the env config file
cat > "$ENV_FILE" <<EOF
# This file is auto-generated by update-env.bash
env = QT_SCALE_FACTOR,$SCALE
env = GDK_SCALE,$SCALE
env = GDK_DPI_SCALE,1
EOF

echo "Updated $ENV_FILE with scale factor = $SCALE"
